### ISSUE TITLE
How to show the records for approval (Help/Advice)

### ISSUE THREAD

**Issue by afarral** [stephenlake/laravel-approval#12]
Hi
I was wondering how you can show the records to be approved, ideally in a table with an approve and reject button.
Thanks

**Comment by stephenlake** [comment]
https://github.com/stephenlake/laravel-approval/issues/6

**Comment by afarral** [comment]
Thank you for that, i have that, the issue i am having is how to access and loop through the json modifications to show this, e.g
"modifcations"=>"......... "enddate": {modified": "27/11/2019" .........

as
`<td>enddate</td><td> 27/11/2019</td>`

![FireShot Capture 015 -  - 127 0 0 1](https://user-images.githubusercontent.com/22122585/69900544-9971f700-136c-11ea-8475-0b1681a3c3b3.png)

**Comment by stephenlake** [comment]
> Thank you for that, i have that, the issue i am having is how to access and loop through the json modifications to show this

This is more of a general PHP question than anything - unrelated to this package.

**PHP:**
```php
foreach ($modification->modifications as $key => $modification) {
     echo "{$key}: {$modification['modified']}".PHP_EOL;
}
```

**Blade:**
```php
@foreach ($modification->modifications as $key => $modification)
      {{ $key }}: {{ $modification['modified'] }}
@endforeach
```

**Collections:**
```php
collect($modification->modifications)->each(function ($modification, $key) {
    echo "{$key}: {$modification['modified']}".PHP_EOL;
});
```
