### ISSUE TITLE
How to set approversRequired to dynamic value ?

### ISSUE THREAD

**Issue by srikilam** [stephenlake/laravel-approval#19]
Please Help !!!
My model
```
class Category extends Model
{
    use RequiresApproval;
    protected $approversRequired = 1;
    

    protected $fillable = [
        'name', 'description'
    ];
}

```
This model want to set approver to 1 or 2 or 3 which condition
How to set approversRequired ?

**Comment by stephenlake** [comment]
The approval process is up to you to define your own business logic. This is outside the scope of the package's responsibility.
