### ISSUE TITLE
Skip approval when creating the model [question]

### ISSUE THREAD

**Issue by mlab817** [stephenlake/laravel-approval#23]
I've tried to google this but can't find the answer anywhere. Basically, I want to skip approval process when the user is just creating a model. The package provides a function:

```
public function requiresApprovalWhen($modifications): bool
{
    // logic for requiring approval or not
    // ideally, i will return false here if the model is just being created
}
```

Upon checking the `$modifications` variable however, it only contains the incoming values. Thus, I can't check if the action is to create a new model or not.

How do I go about this?

**Comment by emregocer** [comment]
I think you could instantiate your model class and fill it with your data then use the [setForcedApprovalUpdate ](https://github.com/cloudcake/laravel-approval/blob/e7527e1920eddab13d8c62c037999e6272b9c4e2/src/Traits/RequiresApproval.php#L166)method on it before saving.

**Comment by mlab817** [comment]
Ok, thanks. will try that.
