### ISSUE TITLE
What is the best way to access all creations and changes on a model?

### ISSUE THREAD

**Issue by jam1e** [stephenlake/laravel-approval#6]
In the documentation, there are examples to get all changes for a given result within a model using 

```
$post = Post::find(1);
$post->modifications()->changed()->get();
```
I'm wanting to create a page to see all unapproved changes to a post, like:

```
$posts = Post::modifications()->changed()->get();
```

and likewise with creations.

A pointer in the right direction would be fantastic!

**Comment by stephenlake** [comment]
Something like this?

```php
use Approval\Models\Modification;

// All modifications with the modified model
Modification::with('modifiable')->get();

// Or a specific model that has modifications?
Post::whereHas('modifications')->get();
```

**Comment by jam1e** [comment]
Apologies for the late reply. This is exactaly what I was after, thank you.
